do
   local Csi = ZO_CreateStringId

   -- Text found in the addon code
   Csi("SI_LTC_TEXT_DISPLAYNAME",                                    "Loot To Chat")
   Csi("SI_LTC_TEXT_GAINED",                                         "Gained")
   Csi("SI_LTC_TEXT_SPENT",                                          "Spent")
   Csi("SI_LTC_TEXT_TOTALS",                                         "Totals")
   Csi("SI_LTC_TEXT_LOOTED",                                         "Looted")
   Csi("SI_LTC_TEXT_COLLECTED",                                      "Collected")
   Csi("SI_LTC_TEXT_STOLEN",                                         "Stolen")
   Csi("SI_LTC_TEXT_QUEST_ITEM",                                     "Quest Item")
   Csi("SI_LTC_TEXT_COLLECTIBLE",                                    "Collectible")
   Csi("SI_LTC_TEXT_RESEARCHABLE",                                   "Researchable")
   Csi("SI_LTC_TEXT_BACKPACK_SPACE",                                 "Backpack Space")
   Csi("SI_LTC_TEXT_NOT_KNOWN",                                      "Not Known")
   Csi("SI_LTC_TEXT_KNOWN",                                          "Known")
   Csi("SI_LTC_TEXT_VOUCHERS",                                       "vouchers")
   Csi("SI_LTC_TEXT_MATERIAL_USED",                                  "Material Used")
   Csi("SI_LTC_TEXT_CRAFTED",                                        "Crafted")
   Csi("SI_LTC_TEXT_COLOR_TRASH",                                    "Trash (gray)")
   Csi("SI_LTC_TEXT_COLOR_NORMAL",                                   "Normal (white)")
   Csi("SI_LTC_TEXT_COLOR_FINE",                                     "Fine/Magic (green)")
   Csi("SI_LTC_TEXT_COLOR_SUPERIOR",                                 "Superior/Arcane (blue)")
   Csi("SI_LTC_TEXT_COLOR_EPIC",                                     "Epic/Artifact (purple)")
   Csi("SI_LTC_TEXT_COLOR_LEGENDARY",                                "Legendary (gold)")
   Csi("SI_LTC_TEXT_ON",                                             "ON")
   Csi("SI_LTC_TEXT_OFF",                                            "OFF")
   Csi("SI_LTC_TEXT_SETTINGS_FOR",                                   "Settings for")
   Csi("SI_LTC_TEXT_USING_CHAR_SETTINGS",                            "Using Character Settings")
   Csi("SI_LTC_TEXT_USING_ACCT_SETTINGS",                            "Using Account Settings")
   Csi("SI_LTC_TEXT_DISPLAY_SELF_LOOT",                              "Display Self Loot")
   Csi("SI_LTC_TEXT_DISPLAY_GROUP_LOOT",                             "Display Group Loot")
   Csi("SI_LTC_TEXT_DISPLAY_CURRENCY",                               "Display Currency")
   Csi("SI_LTC_TEXT_DISPLAY_SCREEN_ANNOUNCEMENTS",                   "Display Screen Announcements")

   -- Text found in LAM description/global section
   Csi("SI_LTC_LAM_DESC_TEXT",                                       "Displays loot/currency in the chat window.")
   Csi("SI_LTC_LAM_GLOBAL_HEADER_NAME",                              "Global Preferences")
   Csi("SI_LTC_LAM_GLOBAL_CHCKBX_CHARPREF_NAME",                     "Use character preferences")
   Csi("SI_LTC_LAM_GLOBAL_CHCKBX_CHARPREF_TOOLTIP",                  "Toggle between character and account based preferences. When this setting is ON each character will have their own settings. When OFF; all characters share the same settings.")
   Csi("SI_LTC_LAM_GLOBAL_CHCKBX_CHARPREF_WARNING",                  "Changing this setting will change the account/character setting for all your characters.")

   -- Text found in LAM general section
   Csi("SI_LTC_LAM_GENERAL_HEADER_NAME",                             "General Preferences")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_ANNOUNCE_NAME",                    "Announce at login")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_ANNOUNCE_TOOLTIP",                 "Display Loot To Chat version and settings at login.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SELFLOOT_NAME",                    "Show self loot")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SELFLOOT_TOOLTIP",                 "Toggles the display of self loot in chat.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_GROUPLOOT_NAME",                   "Show group loot")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_GROUPLOOT_TOOLTIP",                "Toggles the display of group loot in chat.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_CRAFTMTRL_NAME",                   "Show crafted material used")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_CRAFTMTRL_TOOLTIP",                "Toggles the display of crafting materials consumed.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_CURRENCY_NAME",                    "Show currency received or spent")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_CURRENCY_TOOLTIP",                 "Toggles the display of currency.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_ITEMTRAIT_NAME",                   "Display item trait")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_ITEMTRAIT_TOOLTIP",                "Include trait in display of weapons, armor and jewelry.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SETNAMES_NAME",                    "Display set names")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SETNAMES_TOOLTIP",                 "Include set names in the loot description.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_KNOWN_NAME",                       "Display known status")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_KNOWN_TOOLTIP",                    "Include Known / Not Known for recipes, motifs and style pages.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_RSRCHBL_NAME",                     "Display researchable status")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_RSRCHBL_TOOLTIP",                  "Include researchable on armor, jewelry and weapons.")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SHORTTEXT_NAME",                   "Short chat messages")
   Csi("SI_LTC_LAM_GENERAL_CHCKBX_SHORTTEXT_TOOLTIP",                "Use shortened messages without descriptive verbs and labels.")

   -- Text found in LAM player section
   Csi("SI_LTC_LAM_PLAYER_HEADER_NAME",                              "Player Preferences")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_TOTALS_NAME",                       "Show totals")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_TOTALS_TOOLTIP",                    "Toggles the display of totals.")
   Csi("SI_LTC_LAM_PLAYER_DRPDWN_MINQLTY_NAME",                      "Minimum loot quality for display")
   Csi("SI_LTC_LAM_PLAYER_DRPDWN_MINQLTY_TOOLTIP",                   "Restricts the quality of loot to be displayed.")
   Csi("SI_LTC_LAM_PLAYER_DRPDWN_MINCRFTMTRL_NAME",                  "Minimum craft material quality for chat display")
   Csi("SI_LTC_LAM_PLAYER_DRPDWN_MINCRFTMTRL_TOOLTIP",               "Restricts the quality of craft material to be displayed.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_FURNMTRL_NAME",                     "Always display looted furniture material")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_FURNMTRL_TOOLTIP",                  "Override quality setting for furniture material.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_RARECRFT_NAME",                     "Always display rare crafting materials in chat")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_RARECRFT_TOOLTIP",                  "Nirncrux, Hakeijo, Powdered Mother of Pearl, Clam Gall, Dragon's Blood and Dragon's Bile.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_QUEST_NAME",                        "Always display Quest Loot")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_QUEST_TOOLTIP",                     "Ignore quality setting for quest loot.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_COLLECTIBLE_NAME",                  "Always display Collectible Loot")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_COLLECTIBLE_TOOLTIP",               "Ignore quality setting for collectible loot.")
   Csi("SI_LTC_LAM_PLAYER_SLDR_FREEBAG_NAME",                        "Free bag slots warning")
   Csi("SI_LTC_LAM_PLAYER_SLDR_FREEBAG_TOOLTIP",                     "Display a warning when the number of free bag slots is at or below this number.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_BANKED_NAME",                       "Show banked currency for gold on all gold activity")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_BANKED_TOOLTIP1",                   "Toggles the display of banked gold.")
   Csi("SI_LTC_LAM_PLAYER_CHCKBX_BANKED_TOOLTIP2",                   "NOTE: Bank transactions and non-gold currency transactions will display bank totals even when this is off.")

   -- Text found in LAM group section
   Csi("SI_LTC_LAM_GROUP_HEADER_NAME",                               "Group Preferences")
   Csi("SI_LTC_LAM_GROUP_DRPDWN_MINQLTY_NAME",                       "Minimum loot quality for group loot display")
   Csi("SI_LTC_LAM_GROUP_DRPDWN_MINQLTY_TOOLTIP",                    "Restricts the display of group member loot.")
   Csi("SI_LTC_LAM_GROUP_DRPDWN_MINQLTY_LRGGRP_NAME",                "Minimum loot quality displayed for large groups")
   Csi("SI_LTC_LAM_GROUP_DRPDWN_MINQLTY_LRGGRP_TOOLTIP",             "Restricts the display of group member loot for groups larger then four.")
   Csi("SI_LTC_LAM_GROUP_SLDR_LRGGRP_NAME",                          "Suppress loot display for large groups")
   Csi("SI_LTC_LAM_GROUP_SLDR_LRGGRP_TOOLTIP",                       "Only display group loot when the group size is this value or smaller.")
   Csi("SI_LTC_LAM_GROUP_CHCKBX_SETGEAR_NAME",                       "Display group loot only when it is set gear")
   Csi("SI_LTC_LAM_GROUP_CHCKBX_SETGEAR_TOOLTIP",                    "Display ONLY the set gear looted by the group. Group quality settings are ignored. The display set name setting is also ignored and set names are displayed.")

   -- Text found in LAM screen announcement section
   Csi("SI_LTC_LAM_SA_HEADER_NAME",                                  "Screen Announcement Preferences")
   Csi("SI_LTC_LAM_SA_CHCKBX_SCRN_NAME",                             "Display screen announcements")
   Csi("SI_LTC_LAM_SA_CHCKBX_SCRN_TOOLTIP",                          "Toggles the display of high quality loot on the screen.")
   Csi("SI_LTC_LAM_SA_CHCKBX_SND_NAME",                              "Play sound with screen announcements")
   Csi("SI_LTC_LAM_SA_CHCKBX_SND_TOOLTIP",                           "Toggles the use of sound.")
   Csi("SI_LTC_LAM_SA_DRPDWN_MINQLTY_NAME",                          "Minimum loot quality for screen display")
   Csi("SI_LTC_LAM_SA_DRPDWN_MINQLTY_TOOLTIP",                       "Restricts the quality of loot for display on the screen.")
   Csi("SI_LTC_LAM_SA_CHCKBX_RARECRFT_NAME",                         "Always screen announce rare crafting materials")
   --Csi("SI_LTC_LAM_SA_CHCKBX_RARECRFT_TOOLTIP",                      "Screen announce Nirncrux, Hakeijo, Powdered Mother of Pearl, Clam Gall, Dragon's Blood and Dragon's Bile.")
   Csi("SI_LTC_LAM_SA_CHCKBX_CRYSTALS_NAME",                         "Display Transmute Crystals")
   Csi("SI_LTC_LAM_SA_CHCKBX_CRYSTALS_TOOLTIP",                      "Screen announce Transmute Crystals.")

   -- Text found in LAM color selection section
   Csi("SI_LTC_LAM_COLOR_HEADER_NAME",                               "Color Selections")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_SELFLOOT_NAME",                     "Self loot text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_LOOTQUANTITY_NAME",                 "Loot quantity text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_LOOTTOTALS_NAME",                   "Loot totals text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_STOLEN_NAME",                       "Stolen loot text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_CRAFTED_NAME",                      "Crafted loot text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_MTRL_NAME",                         "Material used text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_TRAIT_NAME",                        "Set/trait/style/known/researchable text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_QUEST_NAME",                        "Quest item text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_COLLECTIBLE_NAME",                  "Collectible item text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_GROUP_NAME",                        "Group loot text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_CRRNCYGAINED_NAME",                 "Currency gained text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_CRRNCYSPENT_NAME",                  "Currency spent text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_CRRNCYTOTALS_NAME",                 "Currency totals text")
   Csi("SI_LTC_LAM_COLOR_CLRPCKR_BAGSPACE_NAME",                     "Free bag space warning")
   Csi("SI_LTC_LAM_COLOR_BTTN_RESET_NAME",                           "Reset All Colors to Defaults")
   Csi("SI_LTC_LAM_COLOR_BTTN_RESET_TOOLTIP",                        "Reset all the colors to the default values.")

   -- Text for Currency Change Reason
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_LOOT",                         "Loot")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_VENDOR",                       "Vendor")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_MAIL",                         "Mail")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRADE",                        "Trade")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_QUESTREWARD",                  "Quest Reward")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CONVERSATION",                 "Conversation")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_ACTION",                       "Action")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_COMMAND",                      "Command")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BAGSPACE",                     "Bagspace")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BANKSPACE",                    "Bankspace")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_SOULWEARY",                    "Soulweary")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DEPRECATED_1",                 "Unknown")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BATTLEGROUND",                 "Battleground")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_KILL",                         "Kill")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DEPRECATED_0",                 "Unknown")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_KEEP_UPGRADE",                 "Keep Upgrade")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DECONSTRUCT",                  "Deconstruct")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DEPRECATED_2",                 "Unknown")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_SOUL_HEAL",                    "Soul Heal")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRAVEL_GRAVEYARD",             "Travel")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CASH_ON_DELIVERY",             "Cash On Delivery")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_MEDAL",                        "Medal")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_ABILITY_UPGRADE_PURCHASE",     "Ability Upgrade Purchase")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_HOOKPOINT_STORE",              "Hookpoint Store")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CRAFT",                        "Craft")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_STABLESPACE",                  "Stablespace")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_ACHIEVEMENT",                  "Achievement")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_REWARD",                       "Reward")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_FEED_MOUNT",                   "Feed Mount")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_VENDOR_REPAIR",                "Vendor Repair")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRAIT_REVEAL",                 "Trait Reveal")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRADINGHOUSE_PURCHASE",        "Tradinghouse Purchase")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRADINGHOUSE_REFUND",          "Tradinghouse Refund")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_TRADINGHOUSE_LISTING",         "Tradinghouse Listing")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_REFORGE",                      "Reforge")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PLAYER_INIT",                  "Player Init")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RECIPE",                       "Recipe")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CONSUME_FOOD_DRINK",           "Consume Food Drink")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CONSUME_POTION",               "Consume Potion")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_HARVEST_REAGENT",              "Harvest Reagent")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_KEEP_REPAIR",                  "Keep Repair")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PVP_RESURRECT",                "Pvp Resurrect")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BANK_DEPOSIT",                 "Bank Deposit")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BANK_WITHDRAWAL",              "Bank Withdrawal")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RESPEC_SKILLS",                "Respec Skills")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RESPEC_ATTRIBUTES",            "Respec Attributes")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RESEARCH_TRAIT",               "Research Trait")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BOUNTY_PAID_GUARD",            "Bounty Paid Guard")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_STUCK",                        "Stuck")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_EDIT_GUILD_HERALDRY",          "Edit Guild Heraldry")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_GUILD_TABARD",                 "Guild Tabard")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_GUILD_BANK_DEPOSIT",           "Guild Bank Deposit")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_GUILD_BANK_WITHDRAWAL",        "Guild Bank Withdrawal")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_GUILD_STANDARD",               "Guild Standard")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_JUMP_FAILURE_REFUND",          "Jump Failure Refund")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RESPEC_MORPHS",                "Respec Morphs")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BOUNTY_PAID_FENCE",            "Bounty Paid Fence")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BOUNTY_CONFISCATED",           "Bounty Confiscated")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_GUILD_FORWARD_CAMP",           "Guild Forward Camp")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PICKPOCKET",                   "Pickpocket")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_VENDOR_LAUNDER",               "Vendor Launder")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_RESPEC_CHAMPION",              "Respec Champion")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_LOOT_STOLEN",                  "Loot Stolen")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_SELL_STOLEN",                  "Sell Stolen")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BUYBACK",                      "Buyback")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PVP_KILL_TRANSFER",            "Pvp Kill Transfer")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_BANK_FEE",                     "Bank Fee")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DEATH",                        "Death")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_UNKNOWN",                      "Unknown")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CROWN_CRATE_DUPLICATE",        "Crown Crate Duplicate")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_ITEM_CONVERTED_TO_GEMS",       "Item Converted To Gems")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PURCHASED_WITH_GEMS",          "Purchased With Gems")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_PURCHASED_WITH_CROWNS",        "Purchased With Crowns")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_CROWNS_PURCHASED",             "Crowns Purchased")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_OFFENSIVE_KEEP_REWARD",        "Offensive Keep Reward")
   Csi("SI_LTC_CURRENCY_CHANGE_REASON_DEFENSIVE_KEEP_REWARD",        "Defensive Keep Reward")

end